# Generated by Django 4.0.4 on 2022-04-26 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ismi', models.CharField(max_length=20)),
                ('familyasi', models.CharField(max_length=20)),
                ('yoshi', models.IntegerField(default=16)),
            ],
        ),
    ]
