# Generated by Django 4.0.4 on 2022-05-11 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='info',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
